"""Add Board

Revision ID: 9a1ac7f7b05f
Revises: 9a599eb4384a
Create Date: 2016-11-02 11:09:13.404502

"""

# revision identifiers, used by Alembic.
revision = '9a1ac7f7b05f'
down_revision = '9a599eb4384a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_board'))
    )
    op.add_column('figure', sa.Column('board_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_figure_board_id_board'), 'figure', 'board', ['board_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_figure_board_id_board'), 'figure', type_='foreignkey')
    op.drop_column('figure', 'board_id')
    op.drop_table('board')
    ### end Alembic commands ###
