"""Add Figure

Revision ID: 9a599eb4384a
Revises: 
Create Date: 2016-11-02 10:21:17.555849

"""

# revision identifiers, used by Alembic.
revision = '9a599eb4384a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('figure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.CHAR(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('color', sa.Text(), nullable=True),
    sa.Column('killed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_figure'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('figure')
    ### end Alembic commands ###
